services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: mub
      POSTGRES_PASSWORD: Proje*
    ports:
      - "5432:5432"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge