CREATE SCHEMA IF NOT EXISTS "newsapp";

CREATE TABLE IF NOT EXISTS "newsapp"."users" (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(50) NOT NULL,
    "insert_date" TIMESTAMP DEFAULT timezone('utc', CURRENT_TIMESTAMP) NOT NULL
);